all: cpf

cpf: export LLVM_INSTALL_DEBUG=/u/ziyangx/llvm-workspace-9/llvm-install
cpf: export LLVM_INSTALL_RELEASE=/u/ziyangx/llvm-workspace-9/llvm-install-release
cpf: export NOELLE_INSTALL_DEBUG=/u/sa8/CAT
cpf: export NOELLE_INSTALL_RELEASE=/u/sa8/CAT
cpf: export CPF_ROOT_PATH=/u/ziyangx/cpf-9
cpf:
	make -f Makefile.cpf all
