LEVEL=../../../..

LIBRARYNAME=slamp_hooks
#BUILD_RELINKED=0
#SHARED_LIBRARY=0
#BYTECODE_LIBRARY=1
#ENABLE_BUILT_CLANG=1
#LLVMCC_OPTION=clang

include $(LEVEL)/Makefile.common
CXXFLAGS+=-fexceptions -Wno-inline -O3 -emit-llvm 
#CXXFLAGS+=-fexceptions -emit-llvm -Wno-inline -g -O0
