// llvm intrinsics
{ "memset", 0 },
{ "llvm.memset.p0i8.i32", 0 },
{ "llvm.memset.p0i8.i64", 0 },
{ "memcpy", 0 },
{ "llvm.memcpy.p0i8.p0i8.i32", 0 },
{ "llvm.memcpy.p0i8.p0i8.i64", 0 },
{ "memmove", 0 },
{ "llvm.memmove.p0i8.p0i8.i32", 0 },
{ "llvm.memmove.p0i8.p0i8.i64", 0 },
{ "llvm.va_start", 0 },
{ "llvm.va_end", 0 },
// New with llvm 135637
{  "llvm.lifetime.start", 1},
{  "llvm.lifetime.start.p0i8", 1},
{  "llvm.lifetime.end", 1},
{  "llvm.lifetime.end.p0i8", 1},
{  "llvm.invariant.start",1},
{  "llvm.invariant.end",0},
{  "llvm.invariant.end",2},
{  "llvm.var.annotation",0},
{  "llvm.var.annotation",1},
{  "llvm.var.annotation",2},
{  "llvm.annotation.i8",1},
{  "llvm.annotation.i8",2},
{  "llvm.annotation.i16",1},
{  "llvm.annotation.i16",2},
{  "llvm.annotation.i32",1},
{  "llvm.annotation.i32",2},
{  "llvm.annotation.i64",1},
{  "llvm.annotation.i64",2},
{  "llvm.objectsize.i32",0},
{  "llvm.objectsize.i64",0},

//  string.h
{  "strtod", 1 },
