##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=tpool ppool nq txio specpriv-profile specpriv-executive FullLoopProf nospec-executive headerphi_prof

include $(LEVEL)/Makefile.common
