#!/bin/bash

IN=$1
TMP=`basename $IN .bc`.specpriv-profile-noopt.bc
OUT=`basename $IN .bc`.specpriv-profile.bc

DBG=
if [[ x$DEBUG != x ]]
then
  DBG=$DEBUG
fi

# Determine if the user provided a modifier.
# Valid choices are:
# - memcheck
# - massif
# - gdb
PREFIX=time
if [[ x$GDB != x ]]
then
  PREFIX="gdb --args "
elif [[ x$MASSIF != x ]]
then
  PREFIX="valgrind --tool=massif --heap=yes --massif-out-file=massif.out "
elif [[ x$MEMCHECK != x ]]
then
  PREFIX="valgrind --tool=memcheck --leak-check=yes "
elif [[ x$ECHO != x ]]
then
  PREFIX="echo "
fi

AA=`aa`

LIBS="
  -load $LIBERTY_LIBS_DIR/libUtil.so
  -load $LIBERTY_LIBS_DIR/libLoopProf.so
  -load $LIBERTY_LIBS_DIR/libLAMPLoad.so
  -load $LIBERTY_LIBS_DIR/libRedux.so
  -load $LIBERTY_LIBS_DIR/libPointsToProfiler.so
  -load $LIBERTY_LIBS_DIR/libGraphAlgorithms.so
  -load $LIBERTY_LIBS_DIR/libStrategy.so
  -load $LIBERTY_LIBS_DIR/libOrchestration.so
  -load $LIBERTY_LIBS_DIR/libSpeculation.so"

EXTRA="-basicaa -globals-aa -cfl-steens-aa -tbaa -scev-aa -cfl-anders-aa -objc-arc-aa -scoped-noalias -llvm-aa-results"

echo $PREFIX $NOELLE_BINS_DIR/noelle-load $LIBS $EXTRA -targets -specpriv-profiler $IN -o $TMP -stats 2>&1
$PREFIX $NOELLE_BINS_DIR/noelle-load $LIBS $EXTRA -targets -specpriv-profiler $IN -o $TMP -stats 2>&1
#$PREFIX $NOELLE_BINS_DIR/noelle-load $LIBS $AA $EXTRA -targets -specpriv-profiler $IN -o $TMP -stats 2>&1
#$PREFIX opt $LIBS $AA $EXTRA -specpriv-profiler -debug-only=$DBG $IN -o $TMP -stats 2>&1
opt $TMP -O3 -o $OUT

